version: "3.9"

networks:
 roboshop:
   driver: bridge
volumes:
 mysql:
   driver: local
   driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/dckr/mysql
 redis:
   driver: local
   driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/dckr/redis
 rabbitmq:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/dckr/rabbitmq
 mongodb:
   driver: local
   driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/dckr/mongodb
services:
  web:
    image: web-ui:ver1.1
    container_name: web_container 
    ports:
      - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - mysql
    - shipping
  mongodb:
    image: mongo:ver1.1
    container_name: mongodb
    volumes:
      - mongodb:/data/db  
  catalogue:
    image: catalogue:ver1.1
    container_name: catalogue
    # depends_on:
    #  - mongodb
    depends_on:
    - mongodb
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis:/data 
  user:
    image: user:ver1.1
    container_name: user
    depends_on:
    - mongodb
    - redis
    # depends_on:
    #   - mongodb
    #   - redis
  cart:
    image: cart:ver1.1
    container_name: cart 
    # depends_on:
    #  - catalogue
    #  - mongodb 
    #  - redis
    #  - shipping
  mysql:
    image: mysql:ver1.1
    container_name: mysql 
    volumes:
      - mysql:/var/lib/mysql
    # depends_on:
    #   - shipping
  shipping:
    image: shipping:ver1.1
    container_name: shipping 
    # depends_on:
    #  - mysql
    depends_on:
    - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    volumes:
      - rabbitm:/var/lib/rabbitmq
  payment:
    image: payment:ver1.1
    container_name: payment 
    depends_on:
    - rabbitmq
  ratings:
    image: ratings:ver1.1
    container_name: ratings
    depends_on:
    - mysql 

    

  
  