version: "3.9"

volumes:
 mysql:
   driver: local
   driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/mysql
 mongodb:
   driver: local
   driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/mongodb
redis:
   driver: local
   driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/redis
rabbitmq:
   driver: local
   driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/rabbitmq

networks:
 roboshop:
   driver: bridge 
services:
  web:
    image: web-ui:ver1.1
    container_name: web_container 
    ports:
      - "80:80"
    
    # depends_on:
    #   - catalogue
    #   - mongodb
    #   - user
  catalogue:
    image: catalogue:ver1.1
    container_name: catalogue
    # depends_on:
    #  - mongodb
  mongodb:
    image: mongo:ver1.1
    container_name: mongodb
    volumes:
      - mongodb: /data/db
  user:
    image: user:ver1.1
    container_name: user
    # depends_on:
    #   - mongodb
    #   - redis
  cart:
    image: cart:ver1.1
    container_name: cart 
    # depends_on:
    #  - catalogue
    #  - mongodb 
    #  - redis
    #  - shipping 
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis: /data
  mysql:
    image: mysql:ver1.1
    container_name: mysql 
    volumes:
      - mysql: var/lib/mysql
    # depends_on:
    #   - shipping
  shipping:
    image: shipping:ver1.1
    container_name: shipping 
    # depends_on:
    #  - mysql
  payment:
    image: payment:ver1.1
    container_name: payment 
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    volumes:
      - rabbitmq: /var/lib/rabbitmq
  ratings:
    image: ratings:ver1.1
    container_name: ratings 



      